name: Latest MikkiPastel blog post workflow
on:
  schedule:
    # Runs every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo\'s README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update blog from mikkipastel.com
        uses: gautamkrishnar/blog-post-workflow@1.9.4
        with:
          comment_tag_name: "BLOG"
          feed_list: "https://www.mikkipastel.com/rss/"
          commit_message: "Update mikkipastel.com blog posts"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
  update-readme-with-medium:
    name: Update this repo\'s README with latest medium posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update blog from medium
        uses: gautamkrishnar/blog-post-workflow@1.9.4
        with:
          comment_tag_name: "MEDIUM"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCOnNvgkW2wmQXMuUfKVTmWQ"
          commit_message: "Update medium.com blog posts"
          gh_token: ${{ secrets.GITHUB_TOKEN }}